version: '3'

services:
  webapp:
    image: php:7.2-apache
    volumes:
      - ./etc/php:/usr/local/etc/php
      - ./html:/var/www/html
    ports:
      - 50080:80
  db:
    image: mariadb:10.3
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 53306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=tcirculo
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "58025:8025"
      - "51025:1025"
