  - name: Install SELinux tool:libselinux-python
    yum: name=libselinux-python state=latest
  - name: SELinux's disabled
    selinux: state=disabled
  # - name: Reboot
  #   shell: sleep 2 && shutdown -r now "サーバ再起動"
  #   async: 1
  #   poll: 0
  # - name: SELinuxのDisableでない場合サーバ再起動待ち
  #   local_action: wait_for host={{ inventory_hostname }} port=22 delay=10
