  - name: Install SELinux tool:libselinux-python
    yum: name=libselinux-python state=latest
  - name: SELinux's disabled
    selinux: state=disabled
  # - name: Reboot For SELinux's setting active
  #   shell: sleep 2 && shutdown -r now
  #   async: 0
  #   poll: 0
  # - name: Reboot wait
  #   local_action: wait_for host={{ inventory_hostname }} port=22 delay=10
