version: '2'
services:
  redis:
    image: redis:3.0.5
    container_name: 'my_redis'
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  redis-data:
    driver: local
