version: '3'
services:
  db:
    image: mariadb
    container_name: 'db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db-volumes:/var/lib/mariadb
    ports:
      - "3310:3306"

volumes:
  db-volumes:
    driver: local
