version: '3'
services:
  db:
    image: mariadb
    container_name: 'group-work-202101-db'
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sample_rpg
    volumes:
      - ./db/sqls:/docker-entrypoint-initdb.d
      - group-work-202101-db-volumes:/var/lib/mariadb
    ports:
      - "3310:3306"

  web:
    image: nginx:1.19.6-alpine
    container_name: 'group-work-202101-web'
    volumes:
      - ./web/etc/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/html:/var/www/html/:ro
      - ./schemaspy/dst:/var/www/schemaspy/:ro
    ports:
      - "8080:80"
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

volumes:
  group-work-202101-db-volumes:
    driver: local

