version: '3'
services:
  db:
    image: mariadb
    container_name: 'group-work-202101-db'
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sample_rpg
    volumes:
      - ./db/sqls:/docker-entrypoint-initdb.d
      - group-work-202101-db-volumes:/var/lib/mariadb
    ports:
      - "3310:3306"

volumes:
  group-work-202101-db-volumes:
    driver: local
