# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"
  
  # For avoid, [GuestAdditions seems to be installed (6.0.6) correctly, but not running]
  # https://github.com/dotless-de/vagrant-vbguest/issues/333
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
  end
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2", "--ioapic", "on"]
  end

  config.vm.define "localhost" do |server|
    server.vm.network "private_network", ip: "192.168.33.11"
    
    server.vm.synced_folder "./", "/vagrant", type:"virtualbox", create:true,
    :mount_options => ['dmode=775', 'fmode=775']
    
    server.vm.synced_folder "./repos", "/home/vagrant/workspace/repos", 
      type:"virtualbox", create:true, 
    :mount_options => ['dmode=775', 'fmode=774']

    server.vm.provision :docker, run: "always"
    server.vm.provision :docker_compose, compose_version: "1.21.2", run: "always"
    server.vm.provision "ansible_local" , run: "always" do |a| 
      a.playbook = "config/playbook.yml" 
    end
  end

end
