# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrantをどこで実行しても、問題ないようカレントディレクトリを変更
Dir::chdir(File.dirname(__FILE__)) 

# chefを使用したvagrant provisionを実行
def provision_use_chef (config, node_path, options={})
  # network
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # provision(chef config)
  config.vm.provision :shell, :inline => "ulimit -n 4048"
  config.omnibus.chef_version = :latest   # vagrant plugin install vagrant-omnibusの実行が必要
  config.vm.provision "chef_solo" do |chef|
    chef.nodes_path = "./chef-repo/nodes"
    chef.roles_path = "./chef-repo/roles"
    chef.cookbooks_path = "./chef-repo/site-cookbooks"
    # load recipe(server config)
    chef.json = JSON.parse(File.read(node_path))
    chef.json["options"] = options
  end
end

Vagrant.configure(2) do |config|
  # os
  config.vm.box = "centos7"
  config.vm.box_url = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box"

  # sync folder
  config.vm.synced_folder "./", "/vagrant", :mount_options => ['dmode=777','fmode=666']

  # lamp環境設定
  config.vm.define :lamp do |lamp|
    lamp.vm.hostname = "lamp"
    lamp.vm.network "forwarded_port", guest: 80, host: 8080
    lamp.vm.network "private_network", ip: "192.168.33.10"
    lamp.vm.network "private_network", ip: "192.168.9.10", virtualbox__intnet: "mongos"

    # sync folder
    lamp.vm.synced_folder "./system", "/var/data/system", :mount_options => ['dmode=777','fmode=666']

    provision_use_chef(lamp, "./chef-repo/nodes/default.json")
  end

  # nosqlサーバー群設定
  # mongosサーバー
  mongosOptions = { "rsName": nil, "confType": "mongos" }
  config.vm.define :mongos do |mongos|
    mongos.vm.hostname = "mongos"
    mongos.vm.network "private_network", ip: "192.168.33.91"
    mongos.vm.network "private_network", ip: "192.168.9.11", virtualbox__intnet: "mongos"
    mongos.vm.network "private_network", ip: "192.168.1.19", virtualbox__intnet: "shard1"
    mongos.vm.network "private_network", ip: "192.168.2.19", virtualbox__intnet: "shard2"

    provision_use_chef(mongos, "./chef-repo/nodes/mongodb.json", mongosOptions)
  end
  # configサーバー
  mongodcOptions = { "rsName": nil, "confType": "config" , "host": "192.168.9.12 conf1.mongodb.com"}
  config.vm.define :mongodc do |mongodc|
    mongodc.vm.hostname = "mongodc"
    mongodc.vm.network "private_network", ip: "192.168.33.92"
    mongodc.vm.network "private_network", ip: "192.168.9.12", virtualbox__intnet: "mongos"
    mongodc.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: "shard1"
    mongodc.vm.network "private_network", ip: "192.168.2.10", virtualbox__intnet: "shard2"

    provision_use_chef(mongodc, "./chef-repo/nodes/mongodb.json", mongodcOptions)
  end
  # shard1
  repl1Options = { "rsName": "repl1", "confType": "mongod" }
  config.vm.define :mongods11 do |mongods11|
    mongods11.vm.hostname = "mongods11"
    mongods11.vm.network "private_network", ip: "192.168.33.11"
    mongods11.vm.network "private_network", ip: "192.168.1.11", virtualbox__intnet: "shard1"

    provision_use_chef(mongods11, "./chef-repo/nodes/mongodb.json", repl1Options)
  end
  config.vm.define :mongods12 do |mongods12|
    mongods12.vm.hostname = "mongods12"
    mongods12.vm.network "private_network", ip: "192.168.1.12", virtualbox__intnet: "shard1"

    provision_use_chef(mongods12, "./chef-repo/nodes/mongodb.json", repl1Options)
  end
  config.vm.define :mongods13 do |mongods13|
    mongods13.vm.hostname = "mongods13"
    mongods13.vm.network "private_network", ip: "192.168.1.13", virtualbox__intnet: "shard1"

    provision_use_chef(mongods13, "./chef-repo/nodes/mongodb.json", repl1Options)
  end
  # shard2
  repl2Options = { "rsName": "repl2", "confType": "mongod" }
  config.vm.define :mongods21 do |mongods21|
    mongods21.vm.hostname = "mongods21"
    mongods21.vm.network "private_network", ip: "192.168.33.21"
    mongods21.vm.network "private_network", ip: "192.168.2.11", virtualbox__intnet: "shard2"

    provision_use_chef(mongods21, "./chef-repo/nodes/mongodb.json", repl2Options)
  end
  config.vm.define :mongods22 do |mongods22|
    mongods22.vm.hostname = "mongods22"
    mongods22.vm.network "private_network", ip: "192.168.2.12", virtualbox__intnet: "shard2"

    provision_use_chef(mongods22, "./chef-repo/nodes/mongodb.json", repl2Options)
  end
  config.vm.define :mongods23 do |mongods23|
    mongods23.vm.hostname = "mongods23"
    mongods23.vm.network "private_network", ip: "192.168.2.13", virtualbox__intnet: "shard2"

    provision_use_chef(mongods23, "./chef-repo/nodes/mongodb.json", repl2Options)
  end
end
